POST http://localhost:8080/user
Content-Type: application/json

{
  "nome": "Rodolfo",
  "email": "rodolfo@teste.com",
  "documento": "256318231548",
  "endereco": {
    "rua": "Dez",
    "bairro": "Azul",
    "numero": 874,
    "cep": "12547-789",
    "cidade": "SJC",
    "complemento": "casa"
  }
}

####

GET http://localhost:8080/user?email=rodolfo@teste.com
Content-Type: application/json

###
DELETE http://localhost:8080/user?email=rodolfo@teste.com
Content-Type: application/json